#### In this quiz you're going to do some calculations for your bills. Your net expenditure for the past 5 months has been 1200, 2000, 800, 1500 and 1700. What is your average monthly expenditure.

In [1]:
(1200+2000+800+1500+1700)/5

1440.0

#### In this quiz you're going to do some calculations for a mason. Two rooms in a house needs to be filled. One room is 4 ft wide by 11 ft long, the other is 5 ft wide by 9 ft long.each tile is 1ftx1ft in size

#### 1) How many tiles are needed?
#### 2) You buy 17 packages each containing 6 tiles each. How many tiles will be left over?

In [2]:
# write the code that calculates how many tiles are needed down below
print((4 *11) + (5*9))
# write the code that calculates how many tiles will be left over.
print((17*6)-((4 *11) + (5*9)))

89
13


#### Find the length of the vector with its start coordinates as the origin and the end coordinates as (4,5,6).

> *length = squareroot(x^2 + y^2 + z^2)*

In [3]:
# write your code 
import math
math.sqrt((4**2)+(5**2)+(6**2))


8.774964387392123

#### You are managing your finances using python: 

* complete the tasks mentioned in the comments. and then print the amount left in your bank.

> *Note that this code uses scientific notation to define large numbers. 1.2e6 is equal to        1.2 * 10 ** 6 which is equal to 1200000.*

In [4]:
# the amount of money in your bank account is 1.2e6
amt = 1200000

# money recieved every year in form of salary

salary = 9.3e5

# decrease the salary by 30% as tax paid to the government.
salary -= 0.3*salary


# Add the salary to the bank account amt variable
amt += salary
# increase the amt by 4% that you recieved from the bank as intrest

amt += 0.04*amt
# substract 1.2e5 from amt as the rent paied
amt -= 1.2e5
# print the new value of the amt variable
amt

1805040.0

#### Is **Mumbai** more **dense** than Delhi?
> *Print ***True*** if it is and ***False*** if it is not.*

In [5]:
mum_population, mum_area = 20411000, 4355
del_population, del_area = 30291000, 1484

mum = mum_population/mum_area
delhi = del_population/del_area

# Print True if Mumbai is denser than Delhi, and False otherwise
mum>delhi

False

#### In this question you have to print the accuracy logs of a model in training.

In [6]:
model = "VGG16"
iteration = "150"
accuracy = "67.98"


print("the accuracy of {x} model in {y}th iteration is :{z}".format(y=iteration,z= accuracy,x = model))
# TODO: print a log message using the variables above
# This message should have the same format as this one:
# "the accuracy of ResNET50 model in 100th iteration is: 42.16%"

the accuracy of VGG16 model in 150th iteration is :67.98


In [7]:
name = input('Enter your name :')
team = input('Team name:')
print("Welcome {x}, to the {y} team".format(y = team,x = name))

Enter your name :5
Team name:5
Welcome 5, to the 5 team


#### Use string concatination and len() function to fing the length of a persons complete name and store it in the variable name_length.

#### As a business card designer find if the name can fit into a business card.

In [8]:
given_name = "Rahul"
middle_name = "Shastri"
family_name = "Mishra"

name_length = len(given_name + ' ' +middle_name + ' ' + family_name)

# Now we check to make sure that the name fits within the driving license character limit 20
# Nothing you need to do here
print(name_length)
name_length <= 20

20


True

#### In this quiz, you’ll need to change the types of the input and output data in order to get the result you want.

Calculate and print the total sales for the week from the data provided. Print out a string of the form "This week's total sales: xxx", where xxx will be the actual total of all the numbers. You’ll need to change the type of the input data in order to calculate that total.

In [9]:
mon_sales = "121"
tues_sales = "105"
wed_sales = "110"
thurs_sales = "98"
fri_sales = "95"

#TODO: Print a string with this format: This week's total sales: xxx
# You will probably need to write some lines of code before the print statement.
total_sales = int(mon_sales) + int(tues_sales) + int(wed_sales) + int(thurs_sales) + int(fri_sales)
total_sales = str(total_sales)  #convert the type back!!

print("This week\'s total sales {}".format(total_sales))

This week's total sales 529


#### using indexing you have to print this list like [1,2,3,4,5,6,7,8,9]
lst = [9,8,7,6,5,4,3,2,1]

#### Define a dictionary named population that contains this data:

Keys -> Values

New York -> 17.8

Spain -> 13.3

Dhaka -> 13.0

Mumbai -> 12.5

In [10]:
population = {'Shanghai':17.8,'Istanbul':13.3,'Karachi':13.0,'Mumbai':12.5}

In [11]:
population

{'Shanghai': 17.8, 'Istanbul': 13.3, 'Karachi': 13.0, 'Mumbai': 12.5}

#### Try your hand at working with nested dictionaries. Add another entry, *'is_noble_gas,'* to each dictionary in the *elements* dictionary. After inserting the new entries you should be able to perform these lookups:



---

> print(elements['hydrogen']['is_noble_gas'])<br>
False

> print(elements['helium']['is_noble_gas'])<br>
True

In [12]:
## Compound Data Structures

elements = {'hydrogen': {'number': 1, 'weight': 1.00794, 'symbol': 'H'},
            'helium': {'number': 2, 'weight': 4.002602, 'symbol': 'He'}}

# todo: Add an 'is_noble_gas' entry to the hydrogen and helium dictionaries
# hint: helium is a noble gas, hydrogen isn't

elements['hydrogen']['is_noble_gas'] = False
elements['helium']['is_noble_gas'] = True

print(elements['hydrogen']['is_noble_gas'])
print(elements['helium']['is_noble_gas'])

False
True


#### Write an if statement that lets a student know which of these grades they got based on the number they got in exams, which is stored in the integer variable *marks*.

Marks -> Grade

100-90 -> A+

90-80 -> A

80-70 -> B

70-60 -> C

60-50 -> D

50-40 -> E

<40 -> F

> All of the lower and upper bounds here are inclusive, and marks can only take on positive integer values up to 100.

In your if statement, assign the result variable to a string holding the appropriate message based on the value of marks.

"you have scored *[Grade]* Grade."

In [13]:
marks=int(input("enter your marks"))
if(marks>90):
    print("you score A+")
elif(marks<=90 and marks>80):
    print("you score A")
elif(marks<80 and marks>=70):
    print("you score B")
elif(marks<70 and marks>=60):
    print("you score C")
elif(marks<60 and marks>=50):
    print("you score D")
elif(marks<50 and marks>=40):
    print("you score E")
else:
    print("you score F")


enter your marks55
you score D


In [14]:
marks = int(input())  # use this input to make your submission

# write your if statement here
if marks>100:
    print('enter a valid input')
elif marks>90 and marks <100:
    result = 'A+'
elif marks>80and marks <90:
    result = 'A'
elif marks>70 and marks <80:
    result = 'B'
elif marks>60 and marks <70:
    result = 'C'
else:
    result = 'fail'
print(result)

74
B


#### Depending on where an individual is from we need to tax them appropriately. The states of CA, MN, and NY have taxes of 7.5%, 9.5%, and 8.9% respectively. Use this information to take the amount of a purchase and the corresponding state to assure that they are taxed by the right amount.

In [15]:
state = input()
purchase_amount = 4500
state = state.upper()

if (state == 'CA'):
    tax_amount = .075
    total_cost = purchase_amount*(1+tax_amount)
    result = "Since you're from {}, your total cost is {}.".format(state, total_cost)
    print(result)
elif (state == 'MN'):
    tax_amount = .095
    total_cost = purchase_amount*(1+tax_amount)
    result = "Since you're from {}, your total cost is {}.".format(state, total_cost)
    print(result)
elif (state == 'NY'):
    tax_amount = .089
    total_cost = purchase_amount*(1+tax_amount)
    result = "Since you're from {}, your total cost is {}.".format(state, total_cost)

    print(result)


4500


#### Imagine an air traffic control program that tracks three variables, *altitude*, *speed*, and *propulsion* which for a particular airplane have the values specified below.
```
altitude = 10000
speed = 250
propulsion = "Propeller"
```
For each of the following boolean expressions, work out whether it evaluates to True or False and match the correct value.

-  altitude < 1000 and speed > 100
- (propulsion == "Jet" or propulsion == "Turboprop") and speed < 300 and altitude > 20000
- not (speed > 400 and propulsion == "Propeller")
- (altitude > 500 and speed > 100) or not propulsion == "Propeller"

In [16]:
altitude = 10000
speed = 250
propulsion = "Propeller"

In [17]:
if altitude < 1000 and speed > 100:
    print('first is true')
else:
    print('first is false')
if (propulsion == "Jet" or propulsion == "Turboprop") and speed < 300 and altitude > 20000:
    print('second is true')
else:
    print('second is false')
if not (speed > 400 and propulsion == "Propeller"):
    print('third is true')
else:
    print('third is false')
if (altitude > 500 and speed > 100) or not propulsion == "Propeller":
    print('fourth is true')
else:
    print('fourth is false')

first is false
second is false
third is true
fourth is true


#### Take a number from the user and check if it is even then multiply it with 7 and the ouput of mutiplication will be devided by 4 and at last save the answer in result variable otherwise print not an even number

In [18]:
a = int(input())
if a%2==0:
    result = (a*7)/4
else:
    print('not an even number')

4


In [19]:
lst = [1,2,3,4,5]
for i in lst:
    print(i)
    print(i*2)

1
2
2
4
3
6
4
8
5
10


In [20]:
cities = ['new york city', 'mountain view', 'chicago', 'los angeles']
for city in cities[1:2]:
    print(city)
    print("Done!")

mountain view
Done!


#### Write a for loop below that will print out every whole number that is a multiple of 5 and less than or equal to 30.

In [21]:
# Write a for loop using range() to print out multiples of 5 up to 35  not inclusive
for i in range(5,35,5):
    print(i)

5
10
15
20
25
30


#### Write a for loop that iterates over the names list to create a usernames list. To create a username for each name, make everything lowercase and replace spaces with underscores. Running your for loop over the list:
```
names = ["Joey Tribbiani", "Monica Geller", "Chandler Bing", "Phoebe Buffay"]
```
should create the list:

```
usernames = ["joey_tribbiani", "monica_geller", "chandler_bing", "phoebe_buffay"]
```

> HINT: Use the *.replace()* method to replace the spaces with underscores

In [22]:
names = ["Joey Tribbiani", "Monica Geller", "Chandler Bing", "Phoebe Buffay"]
usernames = []

# write your for loop here
for i in names:
    usernames.append(i.lower().replace(" ","_"))

usernames

['joey_tribbiani', 'monica_geller', 'chandler_bing', 'phoebe_buffay']

#### Write a for loop that iterates over a list of strings, tokens, and counts how many of them are XML tags. 

> XML is a data language similar to HTML. You can tell if a string is an XML tag if it begins with a left angle bracket "<" and ends with a right angle bracket ">". 

Keep track of the number of tags using the variable count.

You can assume that the list of strings will not contain empty strings.

In [23]:
tokens = ['<greeting>', 'Hello World!', '</greeting>']
count = 0

for token in tokens:
    if token[0] == '<' and token[-1] == '>':
        count = count + 1
    
print(count)

2


In [24]:
list = ['<greeting>', 'Hello World!', '</greeting>']

start_tag  = ["<", ">"]
end_tag = ["<", "/", ">"]
start_tagCount = 0
end_tagCount = 0
for i in list:
    if any(x in i for x in start_tag):
        start_tagCount = start_tagCount+1
        
    if any(x in i for x in end_tag):
        end_tagCount  = end_tagCount +1
        
print(start_tagCount)
print(end_tagCount)


2
2


#### Write some code, including a for loop, that iterates over a list of strings and creates a single string, html_str, which is an HTML list. For example, if the list is items = ['first string', 'second string'], printing html_str should output:
```
<ul>
<li>first string</li>
<li>second string</li>
</ul>
```
That is, the string's first line should be the opening tag ```<ul>```. Following that is one line per element in the source list, surrounded by ```<li>``` and ```</li>``` tags. The final line of the string should be the closing tag ```</ul>```.

In [25]:
items = ['first string', 'second string']
html_str = "<ul>\n"  # "\ n" is the character that marks the end of the line,
                     # it does the characters that are after it in html_str
                     # are on the next line

for item in items:
    html_str = html_str + "<li>" + str(item) + "</li>" "\n"

html_str = html_str + "</ul>"

print(html_str)

<ul>
<li>first string</li>
<li>second string</li>
</ul>


#### You would like to count the number of fruits in your basket. In order to do this, you have the following dictionary and list of fruits. Use the dictionary and list to count the total number of fruits, but you do not want to count the other items in your basket.

In [26]:
result = 0
basket_items = {'apples': 4, 'oranges': 19, 'kites': 3, 'sandwiches': 8}
fruits = ['apples', 'oranges', 'pears', 'peaches', 'grapes', 'bananas']

#Iterate through the dictionary

#if the key is in the list of fruits, add the value (number of fruits) to result
count = 0    
for key,value in basket_items.items():
    if key in fruits:
        result += value
        count +=1
result


23

In [27]:
count

2

In [28]:
result = 0
basket_items = {'apples': 4, 'oranges': 19, 'kites': 3, 'sandwiches': 8}
fruits = ['apples', 'oranges', 'pears', 'peaches', 'grapes', 'bananas']

#Iterate through the dictionary
for key, value in basket_items.items():
    for item in fruits:
        #if the key is in the list of fruits, add the value (number of fruits)
        #to result
        if item == key:
            result = result + value

print(result)

23


#### Creat Like given

00
01
02
03
10
11
12
13
20
21
22
23

In [30]:
for i in range(3):
    for j in range(4):
        print(str(i),str(j))

0 0
0 1
0 2
0 3
1 0
1 1
1 2
1 3
2 0
2 1
2 2
2 3


#### Find the factorial of a number using a while loop.

A factorial of a whole number is that number multiplied by every whole number between itself and 1. For example, 6 factorial (written "6!") equals 6 x 5 x 4 x 3 x 2 x 1 = 720. So 6! = 720.

We can write a while loop to take any given number and figure out what its factorial is.

Example: If number is 6, your code should compute and print the product, 720

In [31]:
# number to find the factorial of
number = 6   

# start with our product equal to one
product = 1

# track the current number being multiplied
current = 1

# write your while loop here

    # multiply the product so far by the current number

    # increment current with each iteration until it reaches number

while current<=number:
    product *= current
    current +=1

# print the factorial of number
print(product)

720


#### Now use a for loop to find the factorial!

It will now be great practice for you to try to revise the code you wrote above to find the factorial of a number, but this time, using a for loop. Try it in the code editor below!

In [32]:
# number to find the factorial of
number = 6   

# start with our product equal to one
product = 1

# write your for loop here
for i in range(1,number+1):
    product *= i
# print the factorial of number
print(product)

720


##### Suppose you want to count from some number start_num by another number count_by until you hit a final number end_num. Use break_num as the variable that you'll change each time through the loop. For simplicity, assume that end_num is always larger than start_num and count_by is always positive.

##### Before the loop, what do you want to set break_num equal to? How do you want to change break_num each time through the loop? What condition will you use to see when it's time to stop looping?

##### After the loop is done, print out break_num, showing the value that indicated it was time to stop looping. It is the case that break_num should be a number that is the first number larger than end_num.

In [33]:
end_num= 30
start_num= 3
count_by = 3
break_num = 4
while break_num<end_num:
    start_num +=count_by
    break_num += count_by
# write a while loop that uses break_num as the ongoing number to 
#   check against end_num


print(break_num)

31


## **Break and Continue:**
For Loop iterate over every element in a sequence, while loops iterate over every element untill stopping condition is met.

This is sufficient for most purposes, but sometimes we need more precise control over when we need to end a loop.

In these cases we use the *break* keyword.


This brings us to our next statement sometimes there will be conditions where instead of breaking the loop we will like to skip one iteration of the loop. In this case we will use the continue keyword.

> break and continue keywords, which can be used in both for and while loops.
- break terminates a loop
- continue skips one iteration of a loop

In [34]:
fruits= ["orange", "strawberry", "apple"]
foods = ["apple", "apple", "burger", "toast"]

fruit_count = 0
for food in foods:
  if food not in fruits:
    print("Not a fruit")
    break
  fruit_count += 1
  print("Found a fruit!!")

print("Total fruits: ", fruit_count)

Found a fruit!!
Found a fruit!!
Not a fruit
Total fruits:  2


#### Write a loop with a break statement to create a string, news_ticker, that is exactly 140 characters long. You should create the news ticker by adding headlines from the headlines list, inserting a space in between each headline. If necessary, truncate the last headline in the middle so that news_ticker is exactly 140 characters long.

> Remember that break works in both for and while loops. Use whichever loop seems most appropriate. Consider adding print statements to your code to help you resolve bugs.

In [35]:
headlines = ["Local Bear Eaten by Man",
             "Legislature Announces New Laws",
             "Peasant Discovers Violence Inherent in System",
             "Cat Rescues Fireman Stuck in Tree",
             "Brave Knight Runs Away",
             "Papperbok Review: Totally Triffic"]

news_ticker = ""

headlines = " ".join(headlines)

for letter in headlines:
    news_ticker = news_ticker + letter
    if len(news_ticker) == 140:
        break

print(news_ticker)


Local Bear Eaten by Man Legislature Announces New Laws Peasant Discovers Violence Inherent in System Cat Rescues Fireman Stuck in Tree Brave


In [36]:
headlines = ["Local Bear Eaten by Man",
             "Legislature Announces New Laws",
             "Peasant Discovers Violence Inherent in System",
             "Cat Rescues Fireman Stuck in Tree",
             "Brave Knight Runs Away",
             "Papperbok Review: Totally Triffic"]

news_ticker = ""
for headline in headlines:
    news_ticker += headline + " "
    if len(news_ticker) >= 140:
        news_ticker = news_ticker[:140]
        break

print(news_ticker)

Local Bear Eaten by Man Legislature Announces New Laws Peasant Discovers Violence Inherent in System Cat Rescues Fireman Stuck in Tree Brave


#### Use zip to write a for loop that creates a string specifying the label and coordinates of each point and appends it to the list points. Each string should be formatted as ``` label: x, y, z ``` . For example, the string for the first coordinate should be ```F: 23, 677, 4```.

In [37]:
x_coord = [23, 53, 2, -12, 95, 103, 14, -5]
y_coord = [677, 233, 405, 433, 905, 376, 432, 445]
z_coord = [4, 16, -6, -42, 3, -6, 23, -1]
labels = ["F", "J", "A", "Q", "Y", "B", "W", "X"]

#points = list(zip(labels, x_coord,y_coord,z_coord))
# write your for loop here
lst = []
for labels,x,y,z in zip(labels, x_coord,y_coord,z_coord):
    lst.append("{}:{},{},{}".format(labels,x,y,x))

lst

['F:23,677,23',
 'J:53,233,53',
 'A:2,405,2',
 'Q:-12,433,-12',
 'Y:95,905,95',
 'B:103,376,103',
 'W:14,432,14',
 'X:-5,445,-5']

In [38]:
x_coord = [23, 53, 2, -12, 95, 103, 14, -5]
y_coord = [677, 233, 405, 433, 905, 376, 432, 445]
z_coord = [4, 16, -6, -42, 3, -6, 23, -1]
labels = ["F", "J", "A", "Q", "Y", "B", "W", "X"]

points = []
for point in zip(labels, x_coord, y_coord, z_coord):
    points.append("{}: {}, {}, {}".format(*point))

for point in points:
    print(point)


F: 23, 677, 4
J: 53, 233, 16
A: 2, 405, -6
Q: -12, 433, -42
Y: 95, 905, 3
B: 103, 376, -6
W: 14, 432, 23
X: -5, 445, -1


#### Use zip to create a dictionary cast that uses names as keys and heights as values.

In [39]:
cast_names = ["Joey Tribbiani", "Monica Geller", "Chandler Bing", 
              "Ross Geller", "Phoebe Buffay"]

cast_heights = [172, 168, 172, 166, 170]

cast = dict(zip(cast_names,cast_heights))
print(cast)

{'Joey Tribbiani': 172, 'Monica Geller': 168, 'Chandler Bing': 172, 'Ross Geller': 166, 'Phoebe Buffay': 170}


#### Use zip to transpose data from a 4-by-3 matrix to a 3-by-4 matrix.

In [40]:

data = ((0, 1, 2), (3, 4, 5), (6, 7, 8), (9, 10, 11))

data_transpose = tuple(zip(*data))

print(data_transpose)

((0, 3, 6, 9), (1, 4, 7, 10), (2, 5, 8, 11))


In [41]:
cast_names = ["Barney", "Robin", "Ted", "Lily", "Marshall"]
cast_heights = [72, 68, 72, 66, 76]

cast = dict(zip(cast_names, cast_heights)) 

print(cast)

{'Barney': 72, 'Robin': 68, 'Ted': 72, 'Lily': 66, 'Marshall': 76}


#### Use enumerate to modify the cast list so that each element contains the name followed by the character's corresponding income in $ 1000. For example, the first element of cast should change from "Barney Stinson" to "Barney Stinson 150".

In [42]:
cast = ["Barney Stinson", "Robin Scherbatsky", "Ted Mosby", 
        "Lily Aldrin", "Marshall Eriksen"]
heights = [150, 100, 40, 0, 80]

# write your for loop here
for i, j in enumerate(cast):
    cast[i] = cast[i] +' '+ str(heights[i])

    
print(cast)

['Barney Stinson 150', 'Robin Scherbatsky 100', 'Ted Mosby 40', 'Lily Aldrin 0', 'Marshall Eriksen 80']


#### In Python you can create lists very quickly and consisely with a cool tool called as list comprehension

In [43]:
cities = ['new york city', 'mountain view', 
                      'chicago', 'los angeles']
capitalized_cities = []

for city in cities:
    capitalized_cities.append(city.title())

print(capitalized_cities)

['New York City', 'Mountain View', 'Chicago', 'Los Angeles']


#### With the help of list comprehension this can be reduced to:

In [44]:
capitalized_cities = [city.title() for city in cities]

print(capitalized_cities)

['New York City', 'Mountain View', 'Chicago', 'Los Angeles']


#### Use a list comprehension to create a new list first_names containing just the first names in names in lowercase.

In [45]:
names = ["Barney Stinson", "Robin Scherbatsky", "Ted Mosby", 
        "Lily Aldrin", "Marshall Eriksen"]

first_names = [i.lower().split()[0] for i in names]
print(first_names)

['barney', 'robin', 'ted', 'lily', 'marshall']


#### Use a list comprehension to create a list multiples_3 containing the first 20 multiples of 3.

In [46]:
multiples_3 = [ x for x in range(3, 60+1)  if x % 3 == 0]
print(multiples_3)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60]


In [47]:
# Second solution:

multiples_3 = [x * 3 for x in range(1, 21)]
print(multiples_3)


[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60]


#### Use a list comprehension to create a list of names passed that only include those that scored at least 65.

In [48]:
scores = {
             "Deku": 70,
             "Bakugo": 35,
             "Tenya": 82,
             "Shoto": 23,
             "All Might": 98
          }


passed = [key for key,values in scores.items() if values >=65]
# write your list comprehension here
print(passed)

['Deku', 'Tenya', 'All Might']


#### Write a function named population_density that takes two arguments, population and land_area, and returns a population density calculated from those values. I've included two test cases that you can use to verify that your function works correctly. Once you've written your function, use the Test Run button to test your code.

In [49]:
# write your function here
def population_density(population, land_area):
    return population/land_area



# test cases for your function
test1 = population_density(10, 1)
expected_result1 = 10.0
print("expected result: {}, actual result: {}".format(expected_result1, test1))

test2 = population_density(864816, 121.4)
expected_result2 = 7123.6902801
print("expected result: {}, actual result: {}".format(expected_result2, test2))

expected result: 10.0, actual result: 10.0
expected result: 7123.6902801, actual result: 7123.690280065897


#### Write a function named readable_timedelta. The function should take one argument, an integer days, and return a string that says how many weeks and days that is. For example, calling the function and printing the result like this:

```
print(readable_timedelta(10))
```
should output the following:
```
1 week(s) and 3 day(s).
```

In [50]:
def readable_timedelta(days):
    """
    Return a string of the number of weeks and days included in days.
    Parameters:
    days -- number of days to convert (int)
    Returns:
    string of the number of weeks and days included in days
    """

    week = days // 7
    # % to get the number of days that remain
    day = days % 7
    return "{} week(s) and {} day(s).".format(week, day)

print(readable_timedelta(10))

1 week(s) and 3 day(s).


#### map() is a higher-order built-in function that takes a function and iterable as inputs, and returns an iterator that applies the function to each element of the iterable. The code below uses map() to find the mean of each list in numbers to create the list averages. Give it a test run to see what happens.

Rewrite this code to be more concise by replacing the mean function with a lambda expression defined within the call to map().

In [51]:
numbers = [
              [34, 63, 88, 71, 29],
              [90, 78, 51, 27, 45],
              [63, 37, 85, 46, 22],
              [51, 22, 34, 11, 18]
           ]

def mean(num_list):
    return sum(num_list) / len(num_list)
print(mean(numbers[0]))
print(mean(numbers[1]))
print(mean(numbers[2]))
print(mean(numbers[3]))
averages = list(map(mean, numbers))
print(averages)
map(mean, numbers)

57.0
58.2
50.6
27.2


TypeError: 'list' object is not callable

In [52]:

numbers = [
              [34, 63, 88, 71, 29],
              [90, 78, 51, 27, 45],
              [63, 37, 85, 46, 22],
              [51, 22, 34, 11, 18]
            ]


def mean(num_list):
    return sum(num_list) / len(num_list)

averages = list(map(mean, numbers))
print(averages)


TypeError: 'list' object is not callable

In [53]:
# With lambda:

numbers = [
              [34, 63, 88, 71, 29],
              [90, 78, 51, 27, 45],
              [63, 37, 85, 46, 22],
              [51, 22, 34, 11, 18]
           ]

averages = list(map(lambda x: sum(x) / len(x), numbers))

print(averages)


TypeError: 'list' object is not callable

**<h3>TASK**</h3>
Write a python function find max(a/b) for all (a,b) belongs to {x1, x2, x3}, where x1, x2 and x3 are the numbers passed as an argument to the function.
<br><br>
for e.g: if we pass 1, 2 and 3 to the function , then it should return:

**max( 1/1, 1/2, 1/3, 2/1, 2/2, 2/3, 3/1, 3/2, 3/3 )**
so the answer for the example will be 3 *i.e* 3/1.   

also write an appropriate docstring for that

In [54]:
# your function here
def maximum(a,b,c):
    """
    maximum() function takes three arguments a,b,c 
    and compares different combinations 
    of (a/a, a/b, a/c, b/a, b/b, b/c, c/a, c/b, c/c) 
    and returns the max of it
    """
    new=[]
    val=[a,b,c]
    for i in val:
        for j in val:
            new.append(i/j)
    return max(new)
maximum(1,2,3)


3.0

#### Using the Built-in functions you learned about in the previous lesson, create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive)

In [55]:
import numpy as np

X = np.arange(2,33,2).reshape((4,4))
X

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

#### Try creating the same array using the np.linspace() function.

In [56]:
import numpy as np

X = np.linspace(2,32,16).reshape((4,4))
X

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])

#### Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive). Afterwards use Boolean indexing to pick out only the odd numbers in the array

In [57]:
import numpy as np

X = np.arange(1,26).reshape(5,5)
print(X)
Y = X[X%2==1]
print(Y)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


#### Question:
Use Broadcasting to create a 4 x 4 ndarray that has its first column full of 1s, its second column full of 2s, its third column full of 3s, etc..

In [58]:
# Python 3.x code to demonstrate star pattern
 
# Function to demonstrate printing pattern
def pypart(n):
     
    # outer loop to handle number of rows
    # n in this case
    for i in range(0, n):
     
        # inner loop to handle number of columns
        # values changing acc. to outer loop
        for j in range(0, i+1):
         
            # printing stars
            print("* ",end="")
      
        # ending line after each row
        print("\r")
 
# Driver Code
n = 5
pypart(n)

* 
* * 
* * * 
* * * * 
* * * * * 


In [59]:

# Python 3.x code to demonstrate star pattern
 
# Function to demonstrate printing pattern
def pypart(n):
    myList = []
    for i in range(1,n+1):
        myList.append("*"*i)
    print("\n".join(myList))
 
# Driver Code
n = 5
pypart(n)

*
**
***
****
*****


In [60]:
#python3 code to print pyramid pattern using recursion
def pypart(n):
    if n==0:
        return
    else:
        pypart(n-1)
        print("* "*n)
  
# Driver Code
n = 5
pypart(n)

* 
* * 
* * * 
* * * * 
* * * * * 


In [61]:
rows = int(input("Enter number of rows:"))

for i in range(rows):
    for j in range(i+1):
        print("*", end="")
    print("\n")

Enter number of rows:


ValueError: invalid literal for int() with base 10: ''

In [62]:
rows = int(input("Enter number of rows: "))

k = 0

for i in range(1, rows+1):
    for space in range(1, (rows-i)+1):
        print(end="  ")
   
    while k!=(2*i-1):
        print("* ", end="")
        k += 1
   
    k = 0
    print()

Enter number of rows: 


ValueError: invalid literal for int() with base 10: ''

In [63]:
rows = int(input("Enter number of rows: "))

for i in range(rows, 1, -1):
    for space in range(0, rows-i):
        print("  ", end="")
    for j in range(i, 2*i-1):
        print("* ", end="")
    for j in range(1, i-1):
        print("* ", end="")
    print()


Enter number of rows: 


ValueError: invalid literal for int() with base 10: ''

In [64]:
rows = int(input("Enter the number of rows: "))  
 
for a in range(rows + 1, 0, -1):    
    for b in range(0, a - 1):  
        print("*", end=' ')  
    print(" ")

Enter the number of rows: 


ValueError: invalid literal for int() with base 10: ''

In [65]:
rows = int(input("Enter number of rows: "))

for i in range(rows, 0, -1):
    for j in range(0, i):
        print("* ", end=" ")
    
    print("\n")

Enter number of rows: 


ValueError: invalid literal for int() with base 10: ''

In [66]:
rows = int(input("Enter number of rows: "))

for i in range(rows, 1, -1):
    for space in range(0, rows-i):
        print("  ", end="")
    for j in range(i, 2*i-1):
        print("* ", end="")
    for j in range(1, i-1):
        print("* ", end="")
    print()

Enter number of rows: 


ValueError: invalid literal for int() with base 10: ''